; --------------------------------------------------------------------
; CONFIGURATION DU CLUB (Modifiable par le gérant)
; --------------------------------------------------------------------

[Acces_Administration]
ADMIN_LOGIN = "Admin"
ADMIN_PASSWORD = "admin1234"

[Acces_Licencies]
USER_LOGIN = "Adherent"
USER_PASSWORD = "adherent123"